# Generated by ZhuYun's Simple Compiler.
	.text
	.bss
	.align	4
a:
	.zero	4
	.align	4
b:
	.zero	4
	.align	4
t0:
	.zero	4

	.section	.rodata
STR0:
	.string	"test:%d\n"

	.text
	.globl	main
	.type	main, @function
main:
	movl	$2, %eax
	movl	%eax, b
	movl	b, %eax
	negl	%eax
	movl	%eax,t0
	movl	t0, %eax
	movl	%eax, a
	movl	a,%ebx
	pushl	%ebx
	pushl	$STR0
	call	printf
	addl	$8,%esp
	movl	$0,%eax
	ret
.section	.note.GNU−stack,"",@progbits
