# Generated by ZhuYun's Simple Compiler.
	.text
	.bss
	.align	4
a:
	.zero	4
	.align	4
b:
	.zero	4

	.section	.rodata
STR0:
	.string	"test:%d\n"

	.text
	.globl	main
	.type	main, @function
main:
	movl	$3, %eax
	movl	%eax, a
	movl	$0, %eax
	movl	%eax, b
.L0:
	movl	b, %eax
	movl	%eax,%ebx
	movl	$6, %eax
	cmpl	%ebx,%eax
	setg	%al
	jl		.L1
	jmp		.L2
.L1:
	movl	a, %eax
	movl	%eax,%ebx
	movl	$1, %eax
	addl	%ebx,%eax
	movl	%eax, a
.L3:
	movl	b, %eax
	movl	%eax,%ebx
	movl	$1, %eax
	addl	%ebx,%eax
	movl	%eax, b
	jmp		.L0
.L2:
	movl	a,%ebx
	pushl	%ebx
	pushl	$STR0
	call	printf
	addl	$8,%esp
	ret
.section	.note.GNU−stack,"",@progbits
